- name: import default vars
  import_role:
    name: UniversalConfig
    defaults_from: platform_defaults.yml

- name: Configure NTP server on BIG-IP
  bigip_device_ntp:
    provider: "{{ provider }}"
    ntp_servers: "{{ntp_servers}}"
  delegate_to: localhost

- name: Configure SNMP trap on BIG-IP
  bigip_snmp_trap:
    provider: "{{ provider }}"
    name: "{{item.name}}"
    version: "{{item.version}}"
    snmp_username: "{{item.snmp_username}}"
    snmp_auth_protocol: "{{item.snmp_auth_protocol}}"
    snmp_auth_password: "{{item.snmp_auth_password}}"
    snmp_privacy_protocol: "{{item.snmp_privacy_protocol}}"
    snmp_privacy_password: "{{item.snmp_privacy_password}}"
    oid: "{{item.oid}}"
    access: "{{item.access}}"
  delegate_to: localhost
  loop: "{{snmp_servers.list}}"
