- name: import default vars
  import_role:
    name: UniversalConfig
    defaults_from: platform_defaults.yml



- name: Configure NTP server on BIG-IP
  bigip_device_ntp:
    provider: "{{ provider }}"
    ntp_servers: "{{ntp_servers}}"
  delegate_to: localhost
