- name: import default vars
  import_role:
    name: UniversalConfig
    defaults_from: platform_defaults.yml

- name: Configure NTP server on BIG-IP {{provider.server}}
  bigip_device_ntp:
    provider: "{{ provider }}"
    ntp_servers: "{{ntp_servers}}"
  delegate_to: localhost

- name: Configure SNMP agent on BIG-IP {{provider.server}}
  bigip_snmp_community:
    provider: "{{ provider }}"
    name: "{{snmp_loop.name}}"
    version: "{{snmp_loop.version}}"
    snmp_username: "{{snmp_loop.snmp_username}}"
    snmp_auth_protocol: "{{snmp_loop.snmp_auth_protocol}}"
    snmp_auth_password: "{{snmp_loop.snmp_auth_password}}"
    snmp_privacy_protocol: "{{snmp_loop.snmp_privacy_protocol}}"
    snmp_privacy_password: "{{snmp_loop.snmp_privacy_password}}"
    oid: "{{snmp_loop.oid}}"
    access: "{{snmp_loop.access}}"
  delegate_to: localhost
  loop: "{{snmp_servers}}"
  loop_control:
    loop_var: snmp_loop
    label: "{{snmp_loop.name}}"
  register: snmp_result

#- name: debug
#  debug:
#    var: snmp_servers
