---
- name: Onboard an F5 BigIP that has been given the initial mgmt connectivity
  hosts: localhost
  gather_facts: false
  #loop through all hosts in imported CSV
  connection: local

#for each host in CSV
  vars:
    provider:
      user: admin
      password: "{{ password | default('admin') }}"
      server: 192.168.1.100
      validate_certs: no

  tasks:
<<<<<<< HEAD
    # read csv then print vars from csv 
    - name: import vars from csv
      read_csv:
        path: OnboardingTargets.csv
      register: targets
=======
    
    - name: import default vars
      import_role:
        name: UniversalConfig
        defaults_from: platform_defaults.yml
    #- name: license device
    #  bigip_device_license:
    #    license_key: "{{ bigip_onboard_license }}"
    #    provider: "{{ provider }}"
    #  delegate_to: localhost
    #  when: bigip_onboard_license is defined and bigip_onboard_license != ''

    - name: Configure NTP server on BIG-IP
      bigip_device_ntp:
        provider: "{{ provider }}"
        ntp_servers: "{{ntp_servers}}"
      delegate_to: localhost
>>>>>>> a88238624de7e78be636b196ccee49a7903fcc13

    - name: perform tasks from role
      import_role:
        name: UniversalConfig
        tasks_from: onboarding_tasks.yml