---
- name: Onboard an F5 BigIP that has been given the initial mgmt connectivity
  hosts: localhost
  gather_facts: false
  #loop through all hosts in imported CSV
  connection: local


  tasks:
    # read csv then print vars from csv 
    - name: import vars from csv
      read_csv:
        path: OnboardingTargets.csv
      register: targets

    - name: perform tasks from role
      import_tasks: onboarding_tasks.yml
      vars:
        provider:
          user: admin
          password: "{{ password | default('admin') }}"
          server: "{{item.IP}}"
          validate_certs: no
      loop: "{{targets.list}}"
