---
- name: Onboard an F5 BigIP that has been given the initial mgmt connectivity
  hosts: localhost
  gather_facts: false
  #loop through all hosts in imported CSV
  connection: local

#for each host in CSV
#  vars:
#    provider:
#      user: admin
#      password: "{{ password | default('admin') }}"
#      server: 192.168.1.100
#      validate_certs: no

  tasks:
    # read csv then print vars from csv 
    - name: import vars from csv
      read_csv:
        path: OnboardingTargets.csv
      register: targets

    - name: print csv vals
      debug:
        msg: '{{item.IP}}'
      loop: '{{targets.list}}'

    - name: perform tasks from role
      include_role:
        name: UniversalConfig
        tasks_from: onboarding_tasks.yml
      vars:
        provider:
          user: admin
          password: "{{ password | default('admin') }}"
          server: "{{item.IP}}"
          validate_certs: no
      loop: "{{targets.list}}"
